name = "crements"
version = "VERSION"
license = "MIT"
author = "Andre Smit"
maintainer = "freevryheid@gmail.com"
copyright = "Copyright 2022, Andre Smit"
[dependencies]
stdlib.git = "https://github.com/fortran-lang/stdlib"
stdlib.branch = "stdlib-fpm"
[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
[install]
library = true
